# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerscribereport',
            name='autogenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='powerscribereport',
            name='report',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerscribereportdatum',
            name='datum_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionattribute',
            name='information_type',
            field=models.CharField(choices=[('Measurement', 'Measurement'), ('Region of Interest', 'Region of Interest'), ('Scanner', 'Scanner'), ('Contrast Type', 'Contrast Type'), ('Contrast Volume', 'Contrast Volume'), ('Contrast Delivery', 'Contrast Delivery'), ('Oral Contrast', 'Oral Contrast'), ('Procedure', 'Procedure')], max_length=50),
        ),
    ]
